-- 006: Restaurants vertical — /eat and /eat/:slug.
-- Restaurants fit the existing generalized schema (immutable rule #2 in
-- CLAUDE.md): no new tables. This migration widens `listings` to carry a
-- slug + theme + freeform config, then seeds the 10 restaurants from
-- _incoming/restaurant-template-engine.jsx and _incoming/seed_restaurants.js.
--
-- NOTE: db/migrations/ is missing 002-004 (hotel seed + the guests-select
-- RLS fix referenced in CLAUDE.md's hard-won lessons) — they were applied
-- directly in Supabase and never committed here. This migration is written
-- defensively around that gap: the listing_type check-constraint rename is
-- looked up dynamically rather than assumed, and no existing RLS is
-- disabled or narrowed. Before running, check pg_policies for name
-- collisions with the policy added at the bottom, and re-test the hotel
-- booking flow from an anonymous/incognito session afterward.

-- ------------------------------------------------------------------
-- 1. Widen listings.listing_type to allow 'restaurant'.
-- The constraint name is looked up rather than assumed, since the table
-- was created in 001_init_schema.sql with an inline (unnamed) check and
-- Postgres's default-naming convention, while reliable, isn't worth
-- gambling a migration on.
-- ------------------------------------------------------------------
do $$
declare
  cname text;
begin
  select conname into cname
  from pg_constraint
  where conrelid = 'listings'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) ilike '%listing_type%';

  if cname is not null then
    execute format('alter table listings drop constraint %I', cname);
  end if;

  alter table listings add constraint listings_listing_type_check
    check (listing_type in ('room', 'tour', 'vehicle', 'table', 'restaurant'));
end $$;

-- ------------------------------------------------------------------
-- 2. New columns on listings: slug (stable, lowercase-hyphenated, used by
-- /eat/:slug), theme_id (selects a preset from features/restaurants/themes.js),
-- site_config (the full restaurant config: tagline, cuisine, story, menu,
-- hours, gallery — see api.js's mapListingToRestaurant for the read shape).
-- ------------------------------------------------------------------
alter table listings add column if not exists slug text;
alter table listings add column if not exists theme_id text default 'enda-mama';
alter table listings add column if not exists site_config jsonb not null default '{}'::jsonb;

-- ------------------------------------------------------------------
-- 3. Backfill slugs for pre-existing (hotel) listings so the column can
-- eventually become NOT NULL. Hotel room-type listings have no slug
-- concept in the app today (hotel routing is by partner id), so these are
-- generated, not curated: "<hotel>-<room type>" plus a short id suffix to
-- guarantee uniqueness even where names collide across hotels (e.g. two
-- "Standard Room" listings).
-- ------------------------------------------------------------------
update listings l
set slug = trim(both '-' from lower(regexp_replace(p.name || '-' || l.name, '[^a-zA-Z0-9]+', '-', 'g')))
           || '-' || substr(l.id::text, 1, 8)
from partners p
where l.partner_id = p.id
  and l.slug is null;

-- ------------------------------------------------------------------
-- 4. Seed data: 10 fictional restaurants (is_seed: true in site_config —
-- same convention as the seed hotels). 3 from the prototype
-- (restaurant-template-engine.jsx), 7 from seed_restaurants.js.
-- Bar Vittoria has no theme_id in the prototype (theme was picked via the
-- dev preview dropdown there); assigned 'asmarina' here for the literal
-- art-deco-ceiling match against that theme's mood.
-- ------------------------------------------------------------------
insert into partners (business_type, name, city, address, phone, status) values
  ('restaurant', 'Adulis Kitchen', 'Asmara', 'Harnet Avenue 42, Asmara, Eritrea', '+291 1 12 34 56', 'active'),
  ('restaurant', 'Marea', 'Massawa', 'Old Port Road 7, Massawa, Eritrea', '+291 1 55 22 10', 'active'),
  ('restaurant', 'Bar Vittoria', 'Asmara', 'Liberation Avenue 15, Asmara, Eritrea', '+291 1 20 11 88', 'active'),
  ('restaurant', 'Ghenet Garden', 'Asmara', 'Sematat Avenue 88, Asmara, Eritrea', '+291 1 18 40 22', 'active'),
  ('restaurant', 'Dolce Asmara', 'Asmara', 'Harnet Avenue 103, Asmara, Eritrea', '+291 1 12 77 09', 'active'),
  ('restaurant', 'Mai Jah Jah Grill', 'Asmara', 'Mai Jah Jah District, Asmara, Eritrea', '+291 1 15 63 30', 'active'),
  ('restaurant', 'Keren Terrace', 'Keren', 'Giro Fiori Road 5, Keren, Eritrea', '+291 1 40 12 84', 'active'),
  ('restaurant', 'Enda Silka', 'Keren', 'Market Square 12, Keren, Eritrea', '+291 1 40 08 51', 'active'),
  ('restaurant', 'Taulud Fish House', 'Massawa', 'Taulud Causeway 3, Massawa, Eritrea', '+291 1 55 09 47', 'active'),
  ('restaurant', 'Gurgusum Beach Kitchen', 'Massawa', 'Gurgusum Beach Road, Massawa, Eritrea', '+291 1 55 31 26', 'active');

insert into listings (partner_id, listing_type, slug, name, description, requires_payment, theme_id, site_config) values
  ((select id from partners where name = 'Adulis Kitchen' and business_type = 'restaurant'), 'restaurant', 'adulis-kitchen', 'Adulis Kitchen', 'Traditional Eritrean dining in the heart of Asmara', false, 'enda-mama', '{"tagline":"Traditional Eritrean dining in the heart of Asmara","cuisine":"Eritrean · Traditional","est":1987,"story":["For nearly four decades, Adulis Kitchen has served Asmara the way a grandmother serves her family — generously, slowly, and always with fresh injera. Our tsebhi simmers for hours over low heat, and our berbere is ground in-house every week.","Every meal ends the traditional way: a full coffee ceremony, beans roasted at your table, three rounds poured, no one in a hurry."],"signatures":["Zigni Beef","Tsebhi Dorho","Shiro","Coffee Ceremony"],"menu":[{"section":"Traditional Plates","items":[{"name":"Zigni","desc":"Slow-simmered beef in berbere sauce, served on injera","price":9},{"name":"Tsebhi Dorho","desc":"Chicken stew with hard-boiled egg and clarified butter","price":10},{"name":"Shiro","desc":"Silky chickpea purée with garlic and toasted spices","price":7},{"name":"Alicha Birsen","desc":"Mild lentil curry with turmeric and ginger","price":7}]},{"section":"To Share","items":[{"name":"Beyaynetu","desc":"Grand vegetarian platter — five stews on injera for two","price":16},{"name":"Kitcha Fit-fit","desc":"Torn flatbread tossed in spiced butter and yogurt","price":6}]},{"section":"To Finish","items":[{"name":"Coffee Ceremony","desc":"Beans roasted tableside, three traditional rounds","price":5},{"name":"Himbasha","desc":"Sweet celebration bread with cardamom","price":4}]}],"hours":[["Mon – Thu","11:00 – 22:00"],["Fri – Sat","11:00 – 23:30"],["Sunday","12:00 – 21:00"]],"gallery":[{"label":"The dining room","tone":"a"},{"label":"Injera, made daily","tone":"b"},{"label":"Coffee ceremony","tone":"c"},{"label":"The courtyard","tone":"d"}],"phone":"+291 1 12 34 56","address":"Harnet Avenue 42, Asmara, Eritrea","price_range":"$$","is_seed":true}'::jsonb),
  ((select id from partners where name = 'Marea' and business_type = 'restaurant'), 'restaurant', 'marea-massawa', 'Marea', 'The Red Sea, straight to your table', false, 'red-sea', '{"tagline":"The Red Sea, straight to your table","cuisine":"Seafood · Coastal","est":2015,"story":["Marea sits on the old port of Massawa, where our fishermen dock each morning. What they bring is what we cook — grilled whole over charcoal, dressed with lime, cumin, and nothing that hides the sea.","Come at sunset. The terrace faces west across the harbor, and the grilled prawns taste better with the sky on fire."],"signatures":["Charcoal Whole Fish","Harbor Prawns","Octopus Salad"],"menu":[{"section":"From the Grill","items":[{"name":"Whole Red Snapper","desc":"Charcoal-grilled, lime, cumin butter, flatbread","price":18},{"name":"Harbor Prawns","desc":"Half kilo, garlic-chili glaze, charred lemon","price":16},{"name":"Kingfish Steak","desc":"Thick-cut, green pepper sauce","price":15}]},{"section":"Cold & Fresh","items":[{"name":"Octopus Salad","desc":"Tender octopus, red onion, parsley, olive oil","price":11},{"name":"Catch Crudo","desc":"Today''s fish, raw, citrus and sea salt","price":12}]},{"section":"Sides","items":[{"name":"Saffron Rice","desc":"With toasted almonds","price":5},{"name":"Grilled Vegetables","desc":"Market vegetables, charcoal-kissed","price":5}]}],"hours":[["Tue – Sun","12:00 – 23:00"],["Monday","Closed"]],"gallery":[{"label":"Sunset terrace","tone":"a"},{"label":"Morning catch","tone":"b"},{"label":"The charcoal grill","tone":"c"},{"label":"Old port views","tone":"d"}],"phone":"+291 1 55 22 10","address":"Old Port Road 7, Massawa, Eritrea","price_range":"$$$","is_seed":true}'::jsonb),
  ((select id from partners where name = 'Bar Vittoria' and business_type = 'restaurant'), 'restaurant', 'bar-vittoria', 'Bar Vittoria', 'Espresso, pasticceria & aperitivo since 1938', false, 'asmarina', '{"tagline":"Espresso, pasticceria & aperitivo since 1938","cuisine":"Café · Italian-Eritrean","est":1938,"story":["Bar Vittoria has poured espresso under the same art-deco ceiling since 1938. The machine is Italian, the beans are Eritrean highland, and the recipe for our cornetti hasn''t changed in three generations.","Mornings are for macchiato and the newspaper. Evenings, the terrace fills for aperitivo as Liberation Avenue takes its nightly stroll."],"signatures":["Macchiato","Cornetto","Panettone","Aperitivo Hour"],"menu":[{"section":"Caffè","items":[{"name":"Macchiato","desc":"The Asmara classic — espresso stained with foam","price":1.5},{"name":"Cappuccino","desc":"Highland beans, steamed milk","price":2},{"name":"Espresso","desc":"Short, dark, perfect","price":1}]},{"section":"Pasticceria","items":[{"name":"Cornetto","desc":"Baked at dawn — plain, jam, or cream","price":1.5},{"name":"Sfogliatella","desc":"Crisp layered pastry, ricotta and citrus","price":2.5},{"name":"Torta della Nonna","desc":"Custard tart with pine nuts","price":3}]},{"section":"Aperitivo","items":[{"name":"House Spritz","desc":"With olives, chips, and small bites","price":4},{"name":"Panini Board","desc":"Three small panini for the table","price":6}]}],"hours":[["Every day","06:30 – 22:00"]],"gallery":[{"label":"The deco ceiling","tone":"a"},{"label":"Morning pastry case","tone":"b"},{"label":"Terrace at dusk","tone":"c"},{"label":"The 1938 machine","tone":"d"}],"phone":"+291 1 20 11 88","address":"Liberation Avenue 15, Asmara, Eritrea","price_range":"$","is_seed":true}'::jsonb),
  ((select id from partners where name = 'Ghenet Garden' and business_type = 'restaurant'), 'restaurant', 'ghenet-garden', 'Ghenet Garden', 'Highland vegetarian cooking, from garden to injera', false, 'highland', '{"tagline":"Highland vegetarian cooking, from garden to injera","cuisine":"Eritrean · Vegetarian","est":2009,"story":["Ghenet Garden grew out of fasting-day cooking — the Wednesdays and Fridays when Asmara''s kitchens go meatless and, many say, taste their best. We took those dishes and gave them a home of their own, with vegetables from farms just outside the city.","Our courtyard tables sit under an old fig tree. Order the beyaynetu, share it, and take your time."],"signatures":["Beyaynetu","Shiro Tegamino","Hamli","Fresh Juices"],"menu":[{"section":"Fasting Plates","items":[{"name":"Beyaynetu","desc":"The full spread — six vegetable stews on fresh injera","price":8},{"name":"Shiro Tegamino","desc":"Chickpea stew served bubbling in a clay pot","price":6},{"name":"Hamli","desc":"Collard greens sautéed with garlic and green chili","price":5},{"name":"Duba","desc":"Sweet pumpkin stew with ginger and turmeric","price":5}]},{"section":"From the Garden","items":[{"name":"Timtimo","desc":"Spiced red lentils, slow-cooked","price":5},{"name":"Garden Salad","desc":"Tomato, onion, jalapeño, lime — sharp and cold","price":4}]},{"section":"Juices & More","items":[{"name":"Spris","desc":"Layered avocado, mango, and papaya juice","price":3},{"name":"Ginger Lemonade","desc":"Pressed daily, barely sweet","price":2.5}]}],"hours":[["Mon – Sat","10:00 – 21:30"],["Sunday","11:00 – 20:00"]],"gallery":[{"label":"The fig-tree courtyard","tone":"a"},{"label":"Beyaynetu for two","tone":"b"},{"label":"Morning vegetable delivery","tone":"c"},{"label":"Shiro in the clay pot","tone":"d"}],"phone":"+291 1 18 40 22","address":"Sematat Avenue 88, Asmara, Eritrea","price_range":"$","is_seed":true}'::jsonb),
  ((select id from partners where name = 'Dolce Asmara' and business_type = 'restaurant'), 'restaurant', 'dolce-asmara', 'Dolce Asmara', 'Gelato & pasticceria on Harnet Avenue', false, 'fiori', '{"tagline":"Gelato & pasticceria on Harnet Avenue","cuisine":"Gelateria · Pastry","est":1996,"story":["Dolce Asmara churns gelato the old way — small batches, every morning, in machines that came from Italy long before we did. Highland milk makes it richer; the afternoon passeggiata makes it necessary.","The counter is first come, first served. The smile is free."],"signatures":["Pistachio Gelato","Cassata","Zabaglione","Affogato"],"menu":[{"section":"Gelato","items":[{"name":"Pistachio","desc":"The house pride — toasted, never too sweet","price":1.5},{"name":"Highland Cream","desc":"Fior di latte from Asmara dairy","price":1.5},{"name":"Mango & Papaya","desc":"Made from lowland fruit, dairy-free","price":1.5},{"name":"Affogato","desc":"Two scoops drowned in hot espresso","price":2.5}]},{"section":"Pasticceria","items":[{"name":"Cassata","desc":"Sicilian layered sponge with ricotta and candied fruit","price":3},{"name":"Cannoli","desc":"Filled to order so the shell stays crisp","price":2},{"name":"Zabaglione","desc":"Warm whipped custard, Sunday afternoons only","price":3}]},{"section":"To Drink","items":[{"name":"Macchiato","desc":"The Asmara standard","price":1},{"name":"Granita","desc":"Lemon or coffee, crushed ice","price":2}]}],"hours":[["Every day","09:00 – 22:00"]],"gallery":[{"label":"The gelato counter","tone":"a"},{"label":"Cassata, sliced","tone":"b"},{"label":"Passeggiata hour","tone":"c"},{"label":"The original machines","tone":"d"}],"phone":"+291 1 12 77 09","address":"Harnet Avenue 103, Asmara, Eritrea","price_range":"$","is_seed":true}'::jsonb),
  ((select id from partners where name = 'Mai Jah Jah Grill' and business_type = 'restaurant'), 'restaurant', 'mai-jahjah-grill', 'Mai Jah Jah Grill', 'Charcoal, smoke, and late nights by the fountain', false, 'steel-steam', '{"tagline":"Charcoal, smoke, and late nights by the fountain","cuisine":"Grill · Eritrean","est":2018,"story":["Mai Jah Jah Grill does one thing: meat over charcoal, seasoned hard, served hot. The grill runs from noon until the coals die, and on weekends that''s well past midnight.","No reservations needed for the terrace — but the private mezzanine books out fast on Fridays."],"signatures":["Lamb Tibsi","Kwanta Firfir","Mixed Grill Board"],"menu":[{"section":"Over Charcoal","items":[{"name":"Lamb Tibsi","desc":"Cubed lamb flash-seared with rosemary and jalapeño","price":11},{"name":"Mixed Grill Board","desc":"Lamb, beef, and chicken for two, with injera and bread","price":20},{"name":"Half Chicken","desc":"Berbere-rubbed, grilled slow","price":9}]},{"section":"House Classics","items":[{"name":"Kwanta Firfir","desc":"Dried spiced beef tossed with torn injera and butter","price":8},{"name":"Zilzil","desc":"Long-cut beef strips, crisp edges, soft center","price":10}]},{"section":"Sides","items":[{"name":"Grilled Corn","desc":"Charred, lime, chili salt","price":3},{"name":"House Bread","desc":"Baked in the coal oven","price":2}]}],"hours":[["Sun – Thu","12:00 – 23:00"],["Fri – Sat","12:00 – 01:00"]],"gallery":[{"label":"The coal bed","tone":"a"},{"label":"Mixed grill board","tone":"b"},{"label":"Terrace at night","tone":"c"},{"label":"The mezzanine","tone":"d"}],"phone":"+291 1 15 63 30","address":"Mai Jah Jah District, Asmara, Eritrea","price_range":"$$","is_seed":true}'::jsonb),
  ((select id from partners where name = 'Keren Terrace' and business_type = 'restaurant'), 'restaurant', 'keren-terrace', 'Keren Terrace', 'Garden dining under the bougainvillea', false, 'keren-bloom', '{"tagline":"Garden dining under the bougainvillea","cuisine":"Eritrean · Garden Café","est":2012,"story":["Keren is Eritrea''s garden city, and Keren Terrace is its table. We cook with what the surrounding orchards bring in — pomegranates, citrus, prickly pear in season — under a canopy of bougainvillea that blooms most of the year.","Come in the late afternoon when the heat lifts off the valley and the light turns gold."],"signatures":["Fruit of the Day","Chicken Alicha","Pomegranate Juice"],"menu":[{"section":"From the Kitchen","items":[{"name":"Chicken Alicha","desc":"Mild turmeric chicken stew, gentle and golden","price":8},{"name":"Vegetable Beyaynetu","desc":"Garden stews on injera, changes daily","price":7},{"name":"Shahan Ful","desc":"Mashed fava beans with tomato, chili, and warm bread","price":4}]},{"section":"From the Orchards","items":[{"name":"Fruit of the Day","desc":"Whatever Keren''s orchards sent this morning","price":3},{"name":"Prickly Pear Plate","desc":"Peeled and chilled, in season (Jul–Sep)","price":3}]},{"section":"To Drink","items":[{"name":"Pomegranate Juice","desc":"Pressed to order","price":2.5},{"name":"Shahi","desc":"Spiced black tea, Keren style","price":1}]}],"hours":[["Every day","08:00 – 21:00"]],"gallery":[{"label":"Under the bougainvillea","tone":"a"},{"label":"Morning orchard haul","tone":"b"},{"label":"Golden hour on the terrace","tone":"c"},{"label":"Shahi service","tone":"d"}],"phone":"+291 1 40 12 84","address":"Giro Fiori Road 5, Keren, Eritrea","price_range":"$","is_seed":true}'::jsonb),
  ((select id from partners where name = 'Enda Silka' and business_type = 'restaurant'), 'restaurant', 'enda-silka', 'Enda Silka', 'Keren breakfast house — ful, silsi, and strong tea', false, 'sahel', '{"tagline":"Keren breakfast house — ful, silsi, and strong tea","cuisine":"Eritrean · Breakfast House","est":1981,"story":["Enda Silka opens before the Monday camel market does, and has for over forty years. Keren eats breakfast seriously — ful mashed at the table, silsi hot enough to wake you, bread straight from the oven next door.","Traders, drivers, and families share the long tables. You will too."],"signatures":["Shahan Ful","Silsi","Ga''at","Market-Day Breakfast"],"menu":[{"section":"Breakfast","items":[{"name":"Shahan Ful","desc":"Fava beans mashed tableside with oil, chili, onion, egg","price":3.5},{"name":"Silsi","desc":"Fiery tomato-berbere sauce with torn bread for dipping","price":3},{"name":"Ga''at","desc":"Barley porridge with a well of spiced butter and yogurt","price":4},{"name":"Frittata","desc":"Eggs scrambled with tomato, onion, and green pepper","price":3.5}]},{"section":"Market-Day Extras","items":[{"name":"Fata","desc":"Bread soaked in spiced yogurt sauce — Monday special","price":4},{"name":"Liver Tibsi","desc":"Quick-fried, onions and chili","price":5}]},{"section":"To Drink","items":[{"name":"Shahi Adey","desc":"Sweet spiced tea, the Keren way","price":0.5},{"name":"Bun","desc":"Coffee, roasted in the back room","price":1}]}],"hours":[["Mon – Sat","05:30 – 14:00"],["Sunday","06:30 – 12:00"]],"gallery":[{"label":"The long tables","tone":"a"},{"label":"Ful, mashed to order","tone":"b"},{"label":"Market morning rush","tone":"c"},{"label":"The tea kettles","tone":"d"}],"phone":"+291 1 40 08 51","address":"Market Square 12, Keren, Eritrea","price_range":"$","is_seed":true}'::jsonb),
  ((select id from partners where name = 'Taulud Fish House' and business_type = 'restaurant'), 'restaurant', 'taulud-fish-house', 'Taulud Fish House', 'Pick your catch, we bake it in the clay oven', false, 'shuq', '{"tagline":"Pick your catch, we bake it in the clay oven","cuisine":"Seafood · Massawa Style","est":1994,"story":["At Taulud Fish House there is no menu in the usual sense — there is a bed of ice with this morning''s catch on it. You point, we weigh, and the fish goes into the clay oven Massawa-style: slashed, rubbed with berbere, and pressed against the hot oven wall until the skin crackles.","It comes to the table whole, with hot flatbread and our green chili sauce. Eat with your hands. Everyone does."],"signatures":["Clay-Oven Fish","Berbere Prawns","Green Chili Sauce"],"menu":[{"section":"From the Oven","items":[{"name":"Clay-Oven Fish","desc":"Today''s whole fish, berbere crust, baked on the oven wall — priced by weight from","price":12},{"name":"Berbere Prawns","desc":"Blistered in the oven''s mouth, finished with lime","price":14},{"name":"Oven Flatbread","desc":"Baked to order against the same walls as the fish","price":2}]},{"section":"From the Market","items":[{"name":"Grilled Calamari","desc":"Charred fast, cumin and garlic oil","price":10},{"name":"Fish Soup","desc":"Head-and-bones broth, tomato, green chili","price":6}]},{"section":"Sides & Sauces","items":[{"name":"Green Chili Sauce","desc":"The house condiment — ask for extra","price":1},{"name":"Tomato & Onion Salad","desc":"Cold and sharp against the heat","price":3}]}],"hours":[["Every day","11:00 – 15:00"],["Evenings","18:00 – 23:30"]],"gallery":[{"label":"The morning ice bed","tone":"a"},{"label":"Fish on the oven wall","tone":"b"},{"label":"The causeway tables","tone":"c"},{"label":"Whole fish, served","tone":"d"}],"phone":"+291 1 55 09 47","address":"Taulud Causeway 3, Massawa, Eritrea","price_range":"$$","is_seed":true}'::jsonb),
  ((select id from partners where name = 'Gurgusum Beach Kitchen' and business_type = 'restaurant'), 'restaurant', 'gurgusum-beach-kitchen', 'Gurgusum Beach Kitchen', 'Barefoot dining on the Gurgusum shore', false, 'dahlak', '{"tagline":"Barefoot dining on the Gurgusum shore","cuisine":"Beach Grill · Seafood","est":2019,"story":["Gurgusum Beach Kitchen is a grill, a shade canopy, and thirty steps of sand between your table and the Red Sea. We open when the afternoon heat breaks and cook until the last table leaves — Massawa keeps late hours, and so do we.","Swim first. The kingfish skewers taste better after."],"signatures":["Kingfish Skewers","Sunset Platter","Fresh Watermelon Juice"],"menu":[{"section":"Beach Grill","items":[{"name":"Kingfish Skewers","desc":"Cumin-lime marinade, grilled over driftwood coals","price":10},{"name":"Sunset Platter","desc":"Skewers, prawns, and grilled catch for two","price":22},{"name":"Spiced Chicken Wings","desc":"Berbere-honey glaze, charred edges","price":7}]},{"section":"Cold & Fresh","items":[{"name":"Red Sea Ceviche","desc":"Today''s white fish, lime, chili, red onion","price":9},{"name":"Watermelon & Feta","desc":"Ice-cold, mint, black pepper","price":5}]},{"section":"To Drink","items":[{"name":"Fresh Watermelon Juice","desc":"Pressed by the glass or the jug","price":2.5},{"name":"Mango Shake","desc":"Thick enough to need patience","price":3},{"name":"Shahi","desc":"Hot sweet tea, even on the beach","price":1}]}],"hours":[["Every day","16:00 – 01:00"]],"gallery":[{"label":"Thirty steps to the sea","tone":"a"},{"label":"Skewers over coals","tone":"b"},{"label":"Sunset from the canopy","tone":"c"},{"label":"The jug of watermelon","tone":"d"}],"phone":"+291 1 55 31 26","address":"Gurgusum Beach Road, Massawa, Eritrea","price_range":"$$","is_seed":true}'::jsonb);

-- ------------------------------------------------------------------
-- 5. Unique index on slug, now that both the backfill and the seed insert
-- above have given every row a value. Partial (where not null) rather than
-- a NOT NULL constraint — leaves room to tighten to NOT NULL in a later
-- migration once the human has confirmed in Supabase that no row (including
-- any added by hand between now and then) has a null slug.
-- ------------------------------------------------------------------
create unique index if not exists idx_listings_slug on listings(slug) where slug is not null;

-- ------------------------------------------------------------------
-- 6. RLS — additive only. Does not enable or disable RLS on any table:
-- since 002-004 aren't in this repo, this migration can't know whether
-- listings/bookings/guests currently have RLS enabled, and flipping that
-- switch here could silently break the live hotel booking flow. A new,
-- narrowly-scoped SELECT policy is safe to add either way (permissive
-- policies only ever expand access, never restrict) and closes the one
-- gap this migration can be sure of: a listings SELECT policy scoped to
-- hotels wouldn't cover listing_type = 'restaurant'.
--
-- Reservation requests reuse the same guests + bookings insert path
-- createBooking() already uses for hotels (see bookingApi.js) — if that
-- path is already RLS-safe for hotels (it must be; hotels are live), it's
-- RLS-safe for restaurants too, since neither guests nor bookings is
-- discriminated by listing_type. Confirm this from an anonymous/incognito
-- session per CLAUDE.md's hard-won lesson before treating step 5 as done.
-- ------------------------------------------------------------------
create policy "public read restaurant listings" on listings
  for select using (listing_type = 'restaurant');
